"""empty message

Revision ID: 48b24a282f39
Revises: bb709729e714
Create Date: 2022-04-27 19:05:09.929592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b24a282f39'
down_revision = 'bb709729e714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'summary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
