"""empty message

Revision ID: efe329310c28
Revises: 50e4486322b4
Create Date: 2022-04-27 12:19:19.443039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe329310c28'
down_revision = '50e4486322b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarks')
    op.add_column('bookmark', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('bookmark', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_bookmark_title'), 'bookmark', ['title'], unique=False)
    op.create_foreign_key(None, 'bookmark', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookmark', type_='foreignkey')
    op.drop_index(op.f('ix_bookmark_title'), table_name='bookmark')
    op.alter_column('bookmark', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('bookmark', 'user_id')
    op.create_table('bookmarks',
    sa.Column('bookmark_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bookmark_id'], ['bookmark.id'], name='bookmarks_bookmark_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='bookmarks_user_id_fkey'),
    sa.PrimaryKeyConstraint('bookmark_id', 'user_id', name='bookmarks_pkey')
    )
    # ### end Alembic commands ###
