"""empty message

Revision ID: f017cfd7a433
Revises: 48b24a282f39
Create Date: 2022-04-28 08:43:24.380236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f017cfd7a433'
down_revision = '48b24a282f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('blog_name', sa.String(), nullable=True))
    op.add_column('bookmark', sa.Column('blog_img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'blog_img_url')
    op.drop_column('bookmark', 'blog_name')
    # ### end Alembic commands ###
